// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bppvqyqjjgiawrjhdccs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwcHZxeXFqamdpYXdyamhkY2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg2ODYsImV4cCI6MjA2NTQ4NDY4Nn0.ccxo_UObUKE5iyzxI5e0tAjeMHTM_V-_mD_dnoNXKZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);